### ISSUE TITLE
Movie titles with special characters aren't being moved to SAMBA destination

### ISSUE THREAD

**Issue by extricator** [Anthirian/script.service.janitor#78] opened 2019-09-15 16:41 UTC
If you have the "create subfolder" option enabled, movies with titles that contain special characters (like colons, ie "Spider-Man: Into the Spider-Verse") aren't being moved to SAMBA destinations. Colons are a special character in SAMBA filesystems and the addon tries to create a subfolder with these characters and it's causing kodi to error out.

**Comment by Anthirian** [comment] 2019-10-24 21:22
Could you please show me a debug log of this behavior? It is quite hard to determine the root cause of the issue without it.

**Comment by rpgdev** [comment] 2019-10-25 01:28
Don't have a log sorry. You should be able to reproduce it on a samba share. Seems like you have to replace the smb special character before creating the folder to where you're going to move the file since right now it tries to create the folder using the movie title along with the special characters.

**Comment by keppo070** [comment] 2019-10-25 08:09
You can see a snippet here. Its the same issue, I think.  [https://github.com/Anthirian/script.service.janitor/issues/74](url)

Maybe some kind of translation allowed charater for the reserved characters. If smb replace : for an -

Perhaps i'm thinking to simple about it. It would some my problem

**Comment by Anthirian** [comment] 2019-11-21 21:19
I'm not sure what the actual cause of this is. The Kodi API offers a method that would sanitize file paths (including those that contain colons such as this example), which I use prior to moving a file anywhere (see line 552 of `default.py`. Unfortunately I don't have a samba share to test this with at the moment. The log posted in the other issue does not contain that much useful information, so could you please create a full debug log for me to take a look at?

**Comment by keppo070** [comment] 2019-11-23 14:18
I think I need the MakeLegalPath() instead of makeLegalFilename  The issue is not the filename.

**Comment by Anthirian** [comment] 2019-11-23 17:48
Good catch! Back when I took over development I don't think the `MakeLegalPath` method even existed. Please do try your suggested edit, I would love to know if it works.

**Comment by keppo070** [comment] 2019-11-25 10:35
I tried. Got a BIG error. Then I RTFM and it seems this is something for C++ and not for Python. 

I was mistaken... going to try something with getCleanMovieTitle.

**Comment by keppo070** [comment] 2019-12-21 15:01
I solved it but i dont know how to implement it in the source

**Comment by Anthirian** [comment] 2020-05-03 11:31
Should be fixed after merging #81.

**Closed by Anthirian** 2020-05-03 11:31 UTC
