### ISSUE TITLE
Error notification showing during video playback despite being disabled

### ISSUE THREAD

**Issue by mobamoba** [Anthirian/script.service.janitor#93] opened 2021-06-02 22:07 UTC
I'm using Matrix 19.1 with all addons updated and I have notifications disabled and debug notifications disabled within the Janitor app but I still see a Janitor error notification while watching video. I think this must be a bug as notification is turned off and shouldn't be appearing at all during playback. Thanks.

**Comment by Anthirian** [comment] 2021-06-06 18:39
It seems you have found a bug, but it's not related to notifications. I seem to have made an error somewhere, which unfortunately shows even if you disable Janitor's notifications. That is because addons don't have control over these notifications. All I can do is fix the underlying issue, but for that I would like to see a log file with debug logging turned on. Could you please share that with me?

**Comment by mobamoba** [comment] 2021-06-07 10:51
Sure. Kodi debug log or Janitor debug log? And I can't "force" the issue nor am I sure what triggers it so how can I capture it?

**Comment by Anthirian** [comment] 2021-06-09 21:46
If you enable debugging mode in Janitor, you should see more messages being printed in the Kodi logs. Unfortunately you cannot trigger the error unless you know what caused it. I will leave this issue open for a while, so you can come back if you've managed to trigger the issue again.

**Comment by J-o-h-n-M** [comment] 2021-06-13 08:19
I have the same issue, will try to get some logs. But also I can only get Janitor to clean when starting it manually. It has not started automatically at all. If it helps, I was using the version on Github prior to the official release.

**Comment by mobamoba** [comment] 2021-06-13 10:05
Actually I noticed the same with mine too - no more automatic cleaning, just manual.

**Comment by J-o-h-n-M** [comment] 2021-06-13 13:38
I did find this error already.
```
2021-06-12 17:16:27.658 T:13469   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: object of type 'NoneType' has no len()
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.janitor/service.py", line 46, in <module>
                                                       autostart()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.janitor/service.py", line 26, in autostart
                                                       if janitor.exit_status == janitor.STATUS_SUCCESS and len(results) > 0:
                                                   TypeError: object of type 'NoneType' has no len()
                                                   -->End of Python script error report<--
```

**Comment by Anthirian** [comment] 2021-06-13 18:16
That's a helpful start. I now have a point to start trying to reproduce the issue. This seems to be related to the service not automatically cleaning videos too.

**Comment by J-o-h-n-M** [comment] 2021-06-13 19:10
I just noticed that Janitor started cleaning (During playback). Which was the first time I have seen this with the latest version. I went to settings and noticed that I had "Do not clean during playback" disabled. I used to have this always enabled, but was playing with the settings today. So perhaps that helps you further in the bug hunt. I have enabled it now again (have delayed start to 10 and scan interval to 30). Now I hope I get the previous error again so that I can get you the debuglog.

**Comment by J-o-h-n-M** [comment] 2021-06-13 19:36
After Enabling the "Do not clean during playback" setting again, the error popped up indeed. The line just before the error says skipping and then the error pops up. So I think it might be related to the "Do not clean during playback" setting. Let me know if you need more info.

```
2021-06-13 21:31:56.273 T:30557    INFO <general>: Got MEDIA_BUTTON intent: 126, up:true
2021-06-13 21:31:56.323 T:30587   ERROR <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(1)
2021-06-13 21:31:56.359 T:30587   ERROR <general>: CMediaCodecVideoBuffer::ReleaseOutputBuffer error in render(0)
2021-06-13 21:32:05.624 T:30680 WARNING <general>: Janitor: Kodi is currently playing a file. Skipping cleaning.
2021-06-13 21:32:05.680 T:30680   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: object of type 'NoneType' has no len()
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.janitor/service.py", line 46, in <module>
                                                       autostart()
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.service.janitor/service.py", line 26, in autostart
                                                       if janitor.exit_status == janitor.STATUS_SUCCESS and len(results) > 0:
                                                   TypeError: object of type 'NoneType' has no len()
                                                   -->End of Python script error report<--
                                                   
2021-06-13 21:32:06.422 T:30680    INFO <general>: Python interpreter stopped
2021-06-13 21:32:13.090 T:30557    INFO <general>: Got MEDIA_BUTTON intent: 86, up:false
2021-06-13 21:32:13.113 T:30587    INFO <general>: CVideoPlayer::CloseFile()
2021-06-13 21:32:13.113 T:26150    INFO <general>: CVideoPlayer::OnExit()
2021-06-13 21:32:13.119 T:26150    INFO <general>: Closing stream player 1
2021-06-13 21:32:13.119 T:26150    INFO <general>: Waiting for audio thread to exit
2021-06-13 21:32:13.121 T:30587    INFO <general>: VideoPlayer: waiting for threads to exit
2021-06-13 21:32:13.179 T:26166    INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2021-06-13 21:32:13.180 T:26150    INFO <general>: Closing audio device
2021-06-13 21:32:13.204 T:30610    INFO <general>: CActiveAE::ApplySettings - Forcing samplerate to 48000
2021-06-13 21:32:13.204 T:26150    INFO <general>: Deleting audio codec
2021-06-13 21:32:13.208 T:26150    INFO <general>: Closing stream player 2
2021-06-13 21:32:13.208 T:26150    INFO <general>: waiting for video thread to exit
2021-06-13 21:32:13.250 T:26163 WARNING <general>: OutputPicture - timeout waiting for buffer
2021-06-13 21:32:13.251 T:26163    INFO <general>: thread end: video_thread
2021-06-13 21:32:13.252 T:26150    INFO <general>: deleting video codec
2021-06-13 21:32:13.358 T:30557    INFO <general>: Got MEDIA_BUTTON intent: 86, up:true
2021-06-13 21:32:13.526 T:26150    INFO <general>: Closing stream player 3
```

**Comment by mobamoba** [comment] 2021-06-13 22:22
It just did it (the thing where Janitor shows me an error notification while playing) and here's what's in my Kodi log with Janitor set to enable debugging:

```
2021-06-13 18:19:09.922 T:4858  WARNING <general>: Janitor: Kodi is currently playing a file. Skipping cleaning.
2021-06-13 18:19:09.943 T:4858    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'TypeError'>
                                                   Error Contents: object of type 'NoneType' has no len()
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.service.janitor/service.py", line 46, in <module>
                                                       autostart()
                                                     File "/storage/.kodi/addons/script.service.janitor/service.py", line 26, in autostart
                                                       if janitor.exit_status == janitor.STATUS_SUCCESS and len(results) > 0:
                                                   TypeError: object of type 'NoneType' has no len()
                                                   -->End of Python script error report<--
                                                   
2021-06-13 18:19:10.438 T:4858     INFO <general>: Python interpreter stopped
```

**Comment by J-o-h-n-M** [comment] 2021-07-08 06:59
Any idea when this bug will be fixed? Or perhaps if you can indicate what the change is, I can do it locally on my side. Really miss the automatic cleaning.

**Comment by Anthirian** [comment] 2021-07-15 16:37
Hopefully I can get around to fixing it soon. Unfortunately life got in the way, so I didn't have time to figure out the root cause yet.

**Comment by Anthirian** [comment] 2021-07-24 20:32
I think I managed to sort out the issue. Could you please apply the changes shown in https://github.com/Anthirian/script.service.janitor/pull/94 and see if that works for you as well?

**Comment by J-o-h-n-M** [comment] 2021-07-25 05:44
Thanks for the update. I have downloaded the updated version from https://github.com/Anthirian/script.service.janitor/tree/93-fix-error-during-playback , will try to see if it works.

**Comment by J-o-h-n-M** [comment] 2021-07-25 06:17
Just had it running and it now cleaned the watched episode while Kodi was on the main screen!. So it seems that this part is working as it should now. The only thing that I then need to test is if the error does not popup anymore, while watching TV.

**Comment by Anthirian** [comment] 2021-07-25 13:06
Great to hear, thanks for testing. I'll wait a few more days to see if you run into any other issues. If not, I'll push it to the Kodi repositories and it should auto-update.

**Comment by mobamoba** [comment] 2021-07-26 13:34
I haven't seen the error since this change, but it hasn't fixed the other problem of Janitor no longer running automatically and having to run it manually instead. Thanks.

**Comment by Anthirian** [comment] 2021-07-26 16:15
Right. Could you then please leave Kodi running long enough for at least two intervals (configured in settings) and post the entire (not-truncated) `kodi.log` file here or on pastebin?

**Comment by mobamoba** [comment] 2021-07-26 21:43
I don't really feel comfortable uploading my whole log because I access some shares via basic authentication which puts username/password in plaintext. However, Janitor is set to run every 30 minutes and this is literally the only reference to it in the past 3 hours. It's possible this was due to cutting/pasting the changed the code but I don't know:

```
ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndentationError'>
                                                   Error Contents: expected an indented block (service.py, line 27)
                                                     File "/storage/.kodi/addons/script.service.janitor/service.py", line 27
                                                       if results and janitor.exit_status == janitor.STATUS_SUCCESS:
                                                       ^
                                                   IndentationError: expected an indented block
                                                   -->End of Python script error report<--
```

**Comment by Anthirian** [comment] 2021-07-27 15:56
That's okay. Obviously you can sanitize the logs for passwords. I do think that error was caused by an incorrect copy paste. You are better off downloading the entire `service.py` and replacing the one that has the error with the downloaded one. It should not give an error then (at least not this particular one).

**Comment by J-o-h-n-M** [comment] 2021-07-27 16:50
@mobamoba  I think its best to download the whole zip file from here: https://github.com/Anthirian/script.service.janitor/tree/93-fix-error-during-playback  then just go to Kodi and choose to install addon from zip file. If you choose this new one, Janitor gets updated. I did it like this and until now, it works like a charm.

**Comment by mobamoba** [comment] 2021-07-27 18:56
Okay thanks I'll give that a shot.

**Comment by mobamoba** [comment] 2021-07-28 13:48
I did that and it runs fine manually with no errors but it still doesn't run automatically. I leave my box on 24/7 and when I turned it on this morning it had deleted nothing and I had to run it manually at which point it deleted 5 shows. I'm running on Coreelec with Kodi 19.2rc2. I tried turning the service menu off then back on again to see if that would help but it still doesn't run automatically and there are no log errors either.

**Comment by Anthirian** [comment] 2021-07-28 15:16
Are there any other mentions of Janitor taking any action in the debug log? Does it just not find anything to delete?

**Comment by mobamoba** [comment] 2021-07-28 16:19
There's just nothing other than the notations that it tried to run but stopped because I was watching something. The rest of the time, it's as if it's not running at all. And it finds stuff to delete when I run manually.

**Comment by J-o-h-n-M** [comment] 2021-07-28 18:33
Seems I was a bit too quick in thinking it worked. After the initial update, Janitor did clean automatically once. But since then it does not seem to clean anymore. I had it set to not clean during play, and I did see that back in the log as:
`WARNING <general>: Janitor: Kodi is currently playing a file. Skipping cleaning.`

But after turning the switch off ( so then it should clean during playback ), nothing happens. I also don't see any log messages regarding Janitor from that point on.

So the update does seem to have fixed the error message, but Janitor does not seem to run automatically.

Leaving KODI on the home screen will not trigger Janitor

Update: Turning the switch off means that it will scan during playback  so that's what I did after seeing the warning message (Having an option that starts with "Do not" is a bit confusing)

**Comment by Anthirian** [comment] 2021-07-28 19:26
Seems like it's not such an easy fix then. I'll try to do more testing soon and pinpoint the issue so I can ship a proper fix. Thanks for the testing so far.

**Comment by Anthirian** [comment] 2021-08-18 21:56
I think I managed to track down the remaining issue. It was much harder to reproduce the problem than to fix it it seems. Could you please download the latest version as a zip file as mentioned before and give it a test run?

**Comment by J-o-h-n-M** [comment] 2021-08-19 08:43
Thanks, installed it. Will report back in a few days to see if it works now.

**Comment by J-o-h-n-M** [comment] 2021-08-21 09:40
It seems to work correctly now. Whenever I am not watching anything, janitor will start and do its cleaning.

**Comment by mobamoba** [comment] 2021-08-21 13:13
I doesn't for me. I watched some shows yesterday and they're still not cleaned today unless I run Janitor manually.

**Comment by Anthirian** [comment] 2021-08-21 21:37
Please also supply me with a debug log so I can dig deeper.

**Comment by mobamoba** [comment] 2021-08-22 12:02
There's nothing about Janitor in the logs other than when I run it manually and it tells me it ran successfully. It doesn't seem to run automatically at all anymore.

**Comment by J-o-h-n-M** [comment] 2021-08-22 12:28
@mobamoba  You did (re)install it from here? https://github.com/Anthirian/script.service.janitor/tree/93-fix-error-during-playback  this was updated 4 days ago

**Comment by mobamoba** [comment] 2021-08-22 12:29
Yes but I can do the reinstall again and restart Kodi and see if anything changes.

**Comment by Anthirian** [comment] 2021-08-22 23:06
Otherwise I suggest restoring Janitor to default settings and then trying again. Your settings file may have become corrupt.

**Comment by mobamoba** [comment] 2021-08-24 11:40
I don't know if it was the Kodi restart or the reinstall but it's working now thanks.

**Comment by Anthirian** [comment] 2021-08-24 16:11
Great, then I'll proceed to push a new update to the Kodi repositories. You'll then automatically be updated to it if you have that enabled. Thanks for testing 👍🏻

**Closed as completed** 2021-08-25 19:51 UTC
Labels: bug
